version: '3.7'
services:
  web:
    build:
      dockerfile: ./Dockerfile-postgres
    ports:
      - "5000:5000"
    volumes:
      - ./config.py:/app/config.py
    depends_on:
      dbms:
        condition: service_started
    restart: unless-stopped
  dbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "on-failure:3"
volumes:
  database:
    driver: local
